service: lambda-pandas-excel
frameworkVersion: "3"

provider:
  name: aws
  runtime: python3.10

package:
  patterns:
    - "!*/**"
    - "!requirements.txt"
    - "!README.MD"
    - "!pytest.ini"
    - "src/**"

functions:
  main:
    handler: src.handler.main
    layers:
      - arn:aws:lambda:us-east-1:336392948345:layer:AWSSDKPandas-Python310:3
